#pragma once
#ifndef _LEETCODE_1332_H_
#define _LEETCODE_1332_H_
#include <vector>
#include <algorithm>
#include <numeric>
#include <string>
using namespace std;
/*
Given a string s consisting only of letters 'a' and 'b'. 
In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string, 
if it is generated by deleting some characters of a given string without changing its order.

A string is called palindrome if is one that reads the same backward as well as forward.
*/
class Solution1332 {
public:
    int removePalindromeSub(string s) {
        if (s.size() == 0) {
            return 0;
        }
        int x = 0;
        int y = s.size() - 1;
        while (x < y) {
            
        }
    }
    void test() {

    }
};
/*

*/
#endif
